server:
  port: 8004
spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blogs?serverTimezone=UTC
  application:
    name: service-email
  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    port: 6379
    host: 127.0.0.1
# 自定义邮箱配置
mail:
  emailAddr: 2138005605@qq.com
  host: smtp.qq.com
  port: 465
  username: 2138005605@qq.com
  password: pcxeclvelmnzieig # 授权密码， 非邮箱密码，授权码是用于登录第三方邮件客户端的专用密码。
  subject: 个人博客验证码