server:
  port: 8003
spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blogs?serverTimezone=Asia/Shanghai
  application:
    name: service-user
  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
  redis:
    port: 6379
    host: 127.0.0.1
# 阿里云oss配置
aliyun:
  oss:
    file:
      endpoint: oss-cn-shenzhen.aliyuncs.com
      keyid: LTAI5tQKDSjdrJNNk4JPRvRn
      keysecrect: # 阿里云秘钥
      bucketname: edu-200298
